version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"

  dashboard:
    build: .
    command: streamlit run dashboard/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"